<?php
require_once(__DIR__ . '/../vendor/dashticz/security.php');

dashticz_require_same_origin();
dashticz_require_csrf();

if (!isset($_SERVER['REQUEST_METHOD']) || $_SERVER['REQUEST_METHOD'] !== 'POST') {
    dashticz_json_error(405, 'Only POST requests are allowed.');
}

$customDir = __DIR__ . '/../custom';
$configPath = $customDir . '/CONFIG.js';
$defaultConfigPath = $customDir . '/CONFIG_DEFAULT.js';

if (file_exists($configPath)) {
    dashticz_json_error(409, 'CONFIG.js bestaat al.');
}

if (!is_dir($customDir)) {
    if (!mkdir($customDir, 0755, true)) {
        dashticz_json_error(500, 'De map "custom/" bestaat niet en kon niet worden aangemaakt. Maak de map handmatig aan en geef de webserver schrijfrechten.');
    }
} elseif (!is_writable($customDir)) {
    // Try to set write permission — succeeds when PHP runs as the directory owner
    // (e.g. a fresh git clone made by root or a deploy user with PHP as the same user).
    @chmod($customDir, 0775);
    if (!is_writable($customDir)) {
        dashticz_json_error(500, 'De map "custom/" heeft geen schrijfrechten voor de webserver. Voer uit: chmod 775 custom/ (of geef de webserver gebruiker schrijfrechten op deze map).');
    }
}

$allowedKeys = [
    'domoticz_ip', 'app_title', 'theme', 'domoticz_refresh', 'dashticz_refresh',
    'login_timeout', 'editmode', 'loginEnabled', 'client_id', 'client_secret',
    'enable_websocket', 'room_plan', 'use_cors', 'default_cors_url', 'dashticz_php_path',
    'standby_after', 'background_image', 'start_page', 'enable_swiper',
    'vertical_scroll', 'auto_swipe_back_to', 'auto_swipe_back_after', 'auto_slide_pages',
    'slide_effect', 'standard_graph', 'blink_color', 'language',
    'timeformat', 'calendarformat', 'calendarlanguage',
    'auto_positioning', 'use_favorites', 'disable_googleanalytics',
    'last_update', 'hide_topbar', 'edit_mode',
];
$lines = [];

foreach ($allowedKeys as $key) {
    if (!array_key_exists($key, $_POST)) {
        continue;
    }
    $value = json_decode($_POST[$key], true);
    if (json_last_error() !== JSON_ERROR_NONE || is_array($value) || is_object($value)) {
        dashticz_json_error(400, 'Invalid value for setting ' . $key . '.');
    }
    $lines[] = 'config[' . json_encode($key) . '] = ' .
        json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ';';
}

if (empty($lines)) {
    dashticz_json_error(400, 'No valid settings provided.');
}

$generatedContent = "/* Dashticz setup - generated by setup wizard */\n" .
    implode("\n", $lines) . "\n";

$content = $generatedContent;
if (file_exists($defaultConfigPath)) {
    $defaultContent = file_get_contents($defaultConfigPath);
    if ($defaultContent === false) {
        dashticz_json_error(500, 'CONFIG_DEFAULT.js kon niet worden gelezen.');
    }
    $content = rtrim($defaultContent) . "\n\n" . $generatedContent;
}

if (file_put_contents($configPath, $content, LOCK_EX) === false) {
    dashticz_json_error(500, 'Kon CONFIG.js niet schrijven. Controleer of de webserver schrijfrechten heeft op de map "custom/" (bijv. chmod 775 custom/).');
}

header('Content-Type: application/json');
echo json_encode(array('success' => true));
