<?php
require_once(__DIR__ . '/../vendor/dashticz/security.php');

dashticz_require_same_origin();
dashticz_require_csrf();

if (!isset($_SERVER['REQUEST_METHOD']) || $_SERVER['REQUEST_METHOD'] !== 'POST') {
    dashticz_json_error(405, 'Only POST requests are allowed.');
}

$customPath = __DIR__ . '/../custom/custom.js';

if (file_exists($customPath)) {
    dashticz_json_error(409, 'custom.js already exists.');
}

$allowedKeys = [
    'domoticz_ip', 'app_title', 'theme', 'domoticz_refresh', 'dashticz_refresh',
    'login_timeout', 'editmode', 'loginEnabled', 'client_id', 'client_secret',
    'enable_websocket', 'room_plan', 'use_cors', 'default_cors_url', 'dashticz_php_path',
    'standby_after', 'background_image', 'start_page', 'enable_swiper',
    'vertical_scroll', 'auto_swipe_back_to', 'auto_swipe_back_after', 'auto_slide_pages',
    'slide_effect', 'standard_graph', 'blink_color', 'language',
    'timeformat', 'calendarformat', 'calendarlanguage',
    'auto_positioning', 'use_favorites', 'disable_googleanalytics',
    'last_update', 'hide_topbar', 'edit_mode',
];
$lines = [];

foreach ($allowedKeys as $key) {
    if (!array_key_exists($key, $_POST)) {
        continue;
    }
    $value = json_decode($_POST[$key], true);
    if (json_last_error() !== JSON_ERROR_NONE || is_array($value) || is_object($value)) {
        dashticz_json_error(400, 'Invalid value for setting ' . $key . '.');
    }
    $lines[] = 'config[' . json_encode($key) . '] = ' .
        json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ';';
}

if (empty($lines)) {
    dashticz_json_error(400, 'No valid settings provided.');
}

$content = "/* Dashticz setup - generated by setup wizard */\n" .
    implode("\n", $lines) . "\n";

if (file_put_contents($customPath, $content, LOCK_EX) === false) {
    dashticz_json_error(500, 'Unable to write custom.js.');
}

header('Content-Type: application/json');
echo json_encode(array('success' => true));
